### ISSUE TITLE
Future perfect?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#14]
Do we need or even want to introduce the future perfect as a tense in module 1?

I'm not confident to what extent it even exists outside of modern grammar books.

**Comment by mebbott** [comment]
We do not need to introduce it. I feel like have seen it once or twice in texts,but it may have been something labelled future perfect in a lexicon or commentary that was really something else =). I am sure we will not introduce the forms to them at all this year, so let's take it out!

**Comment by neelsmith** [comment]
done. closing
