### ISSUE TITLE
Sequence of topics in module 1

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#15]
I think it makes sense to introduce recessive accent where we've got it now, at the introduction to formation of finite verb forms, and save contract verbs for closer to the end of module 1.  At that time, we can handle accent of contracts (since that's really the only thing about them that's different).

**Comment by mebbott** [comment]
Sounds good! 

Feel free to move things where they make sense to you now, and when can look at the whole together once we have this round of revisions in place.

**Comment by neelsmith** [comment]
Draft text in place: closing.
