### ISSUE TITLE
Dual

### ISSUE THREAD

**Issue by mebbott** [hellenike/textbook#16]
In introducing "number" for finite verbs, we currently have:

> Ancient Greek also has an additional, less common “number” known as the dual, when the subject is two persons, animals, body parts (e.g., eyes, hands), or things acting together.

In introducing "number" for nouns, we currently have:

> Dual is used for two nouns considered a pair; we will not see the dual in our readings this year.

Do we want to state that caveat  about not seeing it this year the first time it is mentioned, both times? In other words, what information about the dual should go where?

**Comment by neelsmith** [comment]
I don't think we need to repeat the warning.

One other option would be to include duals in the *reference* paradigms (not the module summaries) so that if anyone sees a dual on the loose, they could at least compare it to the paradigm?

**Comment by mebbott** [comment]
Made the changes
