### ISSUE TITLE
Name of the language?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#17]
Is it ancient Greek, or Ancient Greek?

**Comment by neelsmith** [comment]
I think I would prefer "ancient Greek".  I realize that parses as a single language continuing in use today which is not really what I mean, but "Greek" is so often used to mean the ancient language with the marked category being "Modern Greek", that I'm hesitant to use "Ancient Greek" as identifying a distinct language.

**Comment by mebbott** [comment]
agreed on "ancient [lower case] Greek"
