### ISSUE TITLE
persistent accents and enclitics

### ISSUE THREAD

**Issue by mebbott** [hellenike/textbook#19]
Right now, I have a brief explanation of persistent accent in the "Overview of nouns" at the beginning of the "Nouns" section of the module. I refer to the "reference" section for patterns of persistent accent, but I can do more here if that seems better.

For enclitics, does it make sense to introduce those in the pronoun section rather than right after persistent accents? I'm thinking that the first and second personal pronouns are common enclitics they will see.

**Comment by neelsmith** [comment]
That's a great idea!

I suggest we go with that and you can close this issue whenever you've got some draft text added there.

**Comment by mebbott** [comment]
added enclitics to pronouns section
