### ISSUE TITLE
nu moveable

### ISSUE THREAD

**Issue by mebbott** [hellenike/textbook#25]
Used it in example without comment, didn't put it in table for imperfect endings, but now have noted it for dative plural endings of third declension nouns.

When should it be introduced? When should we use it or not?

**Comment by neelsmith** [comment]
I think it belongs in unit 1 when we introduce verb forms.  We are, after all, trying to read in context: I think have an alternate form with -ν added, depending on what follows, will not be confusing.

**Comment by mebbott** [comment]
Should we in Module 1 have a brief section on "ease of speaking" practices to avoid hiatus that includes both the nu-moveable and elision, and note that for some forms the nu-moveable was the preferred mode (to retain the vowel instead of eliding it)? Then introduce the practice of noting those forms in paradigms with (ν)?

**Comment by neelsmith** [comment]
I'll add this to Module 1, and close this issue when it's done.

**Comment by mebbott** [comment]
Thanks! I mentioned the nu-moveable for dative plural forms in the 3rd declension as a "note" without putting it in the table of endings. Do we want to indicate it there with (ν)?

**Comment by neelsmith** [comment]
I'd prefer to spell out alternative forms fully.    E.g., in Module 1, I've included an entry in the table of endings for "-ε or -εν" and in paradigms entered third singulars like "ἔδειξε or ἔδειξεν"

**Comment by neelsmith** [comment]
Have completed this for Module 1; closing.

**Comment by mebbott** [comment]
Okay, I will do the same in Module 2
