### ISSUE TITLE
personal pronouns of 3rd person

### ISSUE THREAD

**Issue by mebbott** [hellenike/textbook#28]
Thinking about αὐτός, αὐτή, αὐτό: do all three uses (personal pronoun, intensifying, “the same”) show up in Lysias 1? Should all of them be introduced in Module 2? One or two of them? None of them? (Just introduce 1st and 2nd for now?)

**Comment by neelsmith** [comment]
Assigning myself the job of checking Lysias' usage of αὐτός.  I like the idea of introducing what we actually will read -- ie, not *necessarily* Module 2.

**Comment by mebbott** [comment]
As I work on the reading assignments, I see the 3rd-person pronoun use of αὐτός, αὐτή, αὐτό, and it would be handy to have it for changing first person to third person in the modified readings. But I'm happy to introduce it, note that the nominative for this was never used just as "he, she, it, they" and save the other two uses for the Spring "catch-all" (if we even need to do it then).

**Comment by neelsmith** [comment]
That sounds good to me.  If we're clever, we could even use this to reinforce the Module 1 idea that a finite verb form already has an implied subject with explicit person and number.

**Comment by mebbott** [comment]
assigning to myself adding αὐτός  and that the nominative is never used as a personal pronoun.

**Comment by mebbott** [comment]
done
