### ISSUE TITLE
persistent accent practice

### ISSUE THREAD

**Issue by mebbott** [hellenike/textbook#30]
Persistent accent patterns: as I was working on practice, I realized that when I usually have students practice these for the first time, I am using on first and second declension nouns and adjectives, since most textbooks delay introducing the third declension. And then when we reach the third declension, we practice those patterns on their own. How to do this with all three declensions at the very beginning? Which 3rd declension patterns to practice?

**Comment by neelsmith** [comment]
Assigining to me the task of reviewing 3rd-declension paradigm types:  I've been looking at them this week, should be able to reply to this meaningfully on Friday (tomorrow, as I'm posting this comment).

**Comment by neelsmith** [comment]
We need to include nouns like πόλις  where quantitative metathesis has resulted in "broken" accent rules.
