### ISSUE TITLE
Defer introduction of subjunctive and sequence of moods?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#31]
What if we focused Module 4 on subordination with the optative in secondary sequence since they only know secondary tenses of the indicative?

Spring sequence might be nice if we did something like this after indirect statement:

1. conditions (motivating introduction of subjunctive)
2. present and future tenses of the indicative
3. sequence of moods, and revisit subordination using subjunctive in primary sequence
4. first and second person forms of -ω and -μι verbs?

**Comment by neelsmith** [comment]
Thinking of how the textbook relates to a semester, this might allow us to have a brief unit 4 to wrap up the fall.

**Comment by mebbott** [comment]
[Sent by email, which I mistakenly thought would also show up here:
Hi Neel,

Yes, it makes a lot of sense to not have them learn the subjunctive until after they have learned primary tenses like the present! And I like having the concepts of dependent clauses like the purpose clause and forms of another mood introduced this semester but limiting it to that.

I will work further on Module 4 this weekend and modify it accordingly.

Yours, Mary ]]

Adding that task assignment to me.

**Comment by mebbott** [comment]
**New question**: since we are focusing on the optative alone, should we introduce optative in secondary sequence of indirect statement. We get several examples in Lysias 1.20!

**Comment by mebbott** [comment]
I will make these additions to Module 4

**Comment by mebbott** [comment]
Module 4 now includes Language sections on forms of the optative, purpose clauses in secondary sequence, interrogative and indefinite pronouns, indirect statement and indirect questions as subordinate clauses that can use the optative

**Comment by mebbott** [comment]
Hi Neel,

Yes, it makes a lot of sense to not have them learn the subjunctive until
after they have learned primary tenses like the present! And I like having
the concepts of dependent clauses like the purpose clause and forms of
another mood introduced this semester but limiting it to that.

I will work further on Module 4 this weekend and modify it accordingly.

Yours, Mary
—————
Mary Ebbott
Professor, Department of Classics
College of the Holy Cross
Worcester, MA 01610
(508) 793-2631
