### ISSUE TITLE
style question

### ISSUE THREAD

**Issue by mebbott** [hellenike/textbook#32]
I tend to always put commas and period inside quotation marks, but that is a matter of style. When do you want to put them inside and when outside? Yes, I notice it even though the students likely will not!

**Comment by neelsmith** [comment]
I'd prefer using commas consistently within quotation marks (except in code where that would break the syntax! :-)

**Comment by neelsmith** [comment]
I've globally replaced `",` with `,"` in markdown files for the textbook.

**Comment by mebbott** [comment]
Perfect, thanks! I will follow this style (which is what I prefer, too) in all new additions
