### ISSUE TITLE
Indirect questions in module 4?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#34]
Should we include in module 4 indirect questions, and perhaps both interrogative τίς and the indefinite pronoun?

**Comment by mebbott** [comment]
Will do!

**Comment by mebbott** [comment]
Module 4 now includes Language sections on forms of the optative, purpose clauses in secondary sequence, interrogative and indefinite pronouns, indirect statement and indirect questions as subordinate clauses that can use the optative
