### ISSUE TITLE
Lysias 1 in English?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#35]
We do want the students to read the whole oration in English (even if we assign that in our CBL meeting rather than MWF class time).  Would it be worth including for reference an English translation in the textbook?  If not, of adding a text to our course web sites or Canvas sites?

The Scaife library includes the 1930 Loeb, now out of copyright.  It's of its era, which is to say not exactly easy reading today.  Is that how we want them to get oriented to the speech as a whole?  Or should we save that for later when they can critique its choices in translation after reading a passage in Greek?

**Comment by mebbott** [comment]
I do want them to read the whole oration in English (mainly for CBL). In some ways, I think a more contemporary translation would be better, but the benefit of the older translation is that they hopefully will not think of it as "the answer" to how to translate the Greek. What are our free options? I can look around as well.

**Comment by neelsmith** [comment]
I'd be happier having them look at the Loeb translation only later in the course when they've seen enough of the text in Greek to feel confident critiquing it.  I have not looked around for free texts:  I just had the Scaife browser on my mind since I'd used that source for the Greek text.

**Comment by neelsmith** [comment]
Diotima has a more contemporary translation by Caroline Falkner.  Unfortunately, she cooked up her own language for rights: "Permission is hereby granted to distribute for classroom use, provided that both the translator and Diotima are identified in any such use. Other uses not authorized in writing by the translator or in accord with fair use policy are expressly prohibited."  Especially unfortunate because she died in 2020.  I wonder if our textbook could be considered "classroom use"?  I have no doubt that is within the scope of what she intended more than 20 years ago, but don't have any idea how to ascertain who might be empowered to clarify that or grant permission under a more standard license (such as Creative Commons).

I suppose in the worst case, we could just point to the URL on Diotima.  It would be awfully nice to incorporate something, though, for the sake of simplicity and uniformity.

**Comment by neelsmith** [comment]
Diotima: https://diotima-doctafemina.org/translations/greek/lysias-1-on-the-murder-of-eratosthenes/

**Comment by neelsmith** [comment]
I see that the Women's Classical Caucus took over maintenance of Diotima in 2017.  I wonder if we could clarify with them whether use on a course web site and/or a textbook falls within their view of "classroom use"?

**Comment by mebbott** [comment]
I see that Serena Witzke is named as editor of Diotima v 3.0, so perhaps it would be easy to ask her about incorporating it into our course materials? Do you want me to write to her?

>> If you are interested in contributing course materials, syllabi, translations, or curated bibliographies, please contact the editor, Serena S. Witzke at [switzke@wesleyan.edu](mailto:switzke@wesleyan.edu). All submissions are subject to approval by the site admin. You can also follow us on Twitter [@diotima_v3](https://twitter.com/diotima_v3)

**Comment by neelsmith** [comment]
That would be great!  (On a different note, I wrote to Melisa Cahnmann-Taylor earlier this morning; hope she'll be willing to give us permission to use her poem.)

**Comment by mebbott** [comment]
Okay, I will write to Prof. Witzke. Thanks for writing to Melisa Cahnmann-Taylor!

**Comment by mebbott** [comment]
Forwarding you by email Prof. Witzke's positive reply.

**Comment by neelsmith** [comment]
This is great!  Should I include a fully attributed English translation as an appendix to the textbook do you think?

**Comment by mebbott** [comment]
Yes, I think that would be great!

**Comment by neelsmith** [comment]
Would it be worth including both Falkner's and the Loeb? I can think of lots of ways to compare and critique translations when they get into the text -- in some sections, maybe even in the fall semester.

**Comment by mebbott** [comment]
Yes, including both would be worthwhile, I think. It would also avoid the unintended implication that Falkner's translation is "the answer." Thanks!

**Comment by neelsmith** [comment]
added
