### ISSUE TITLE
Formatting of newly introduced terms?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#36]
When we introduce a technical term for the first time (such as "person", "number"), how should we highlight this?

I think we currently include examples of **strong emphasis**, *emphasis* and "quotation."

Label this question, "Yet another question about compulsive consistency in editing"

**Comment by mebbott** [comment]
Yes, we need a style sheet =).

For first introduction of technical terms, I think I favor **strong emphasis**. Does that seem okay to you?

**Comment by neelsmith** [comment]
I like **strong emphasis**, too.

And  I like the idea of a style sheet!  I've made a page on the repository wiki where we can compile editorial decisions:  https://github.com/hellenike/textbook/wiki/House-style

**Comment by neelsmith** [comment]
Formatting new vocabulary in preliminaries and module 1 for this convention, and closing this issue.  If we want an issue for fully proofing a draft of the textbook against a stylesheet, we can add a new issue.
