### ISSUE TITLE
Unfulfilled promises: the agent of passive verbs

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#50]
The current draft promises at one point to introduce using the genitive to express the agent of passive verbs. Later, reference is made (nice passive!) to the discussion of that topic. But I don't see it anywhere yet.  Where is the best place to add that topic?

**Comment by mebbott** [comment]
Hi Neel,

It is in Module 2, at the end of the section on Prepositions

**Comment by neelsmith** [comment]
Ah ha!  Thank you!
