### ISSUE TITLE
youtubes combining audio, highlighted text and translation?

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#6]
Are these examples a model we should consider?

https://ancientgreek.eu/index.html

**Comment by mebbott** [comment]
Forgot to mention today that I think these can be fun resources. He reads ancient Greek prose out loud much more fluently than I! It would be another option for students to experience the language *as a language*.

**Comment by neelsmith** [comment]
I'll try to pursue with David Banville getting some tech help on this.

**Comment by neelsmith** [comment]
We could do a very low-tech version for just vocalizing Greek -- e.g., preliminaries section on pronounciation -- and for reading a phrase at a time if we might one slide per highlighted section and just did a screen recording.  Overlay of translation would take more work that I think David could help with.  Maybe proceed in 2 steps: 1) do simple reading of Greek, then try 2) adding overlay of translation ?

**Comment by neelsmith** [comment]
I've asked ITS to create a hellenike@holycross.edu account that we could all have access to, so that we could then have a "hellenike" youtube channel.

**Comment by mebbott** [comment]
Great, thanks!

**Comment by neelsmith** [comment]
ITS seems to be progressing on this.  I'm going to close this issue, and open a separate issue about uploading specific videos.
