### ISSUE TITLE
Highlighting/formatting texts for reading

### ISSUE THREAD

**Issue by neelsmith** [hellenike/textbook#9]
Latin 101/102 quasi-standardized some conventions for highlighting certain syntactic functions (principal verbs; subordinating conjunctions + subordinate verbs; sub/obj relations to finite verbs, participles or infinitives; etc.)

There's obvious pedagogical value to consistency in both presentation and potentially assignments ("Mark all principal verbs with the standard convention you've seen in your textbook's presentation").  Should we consider doing this in the textbook?  Perhaps even coordinate with the Latin project so HC students could potentially see a consistent set of conventions in multiple courses in two languages?

**Comment by mebbott** [comment]
Answered in email, copy to Dominic: yes!

**Comment by neelsmith** [comment]
I've put an example in a reading assignment for module 1.  I'm going to close this general issue: we can file more specific issues if we want to add highlighting for particular features of language.
